const Sdata = [
  {
    Id: 1,
    imgSrc:"https://m.media-amazon.com/images/M/MV5BMzA0YzQzODctMDllYi00Nzk0LWIxNjQtNjAxMTZkY2YzMjlkXkEyXkFqcGdeQXVyMTA4NjE0NjEy._V1_FMjpg_UX600_.jpg",
    mName:"Tamasha",
    Ref:"https://www.netflix.com/in/title/80087743",
    info2:"Netflix",
    YRef:"https://www.youtube.com/watch?v=o-e5eWVCzx8",
  },
  {
    Id: 2,
    imgSrc:"https://upload.wikimedia.org/wikipedia/en/9/90/Satyaprem_Ki_Katha_poster.jpg",
    mName:"Satyaprem Ki Katha",
    Ref:"https://primevideo.com/detail/Satyaprem-Ki-Katha/0LZ2E62QE2TFXNTGOA0YSBO2JL",
    info2:"Prime Video",
    YRef:"https://www.youtube.com/watch?v=8EPJiFfWRfw",
  },
  {
    Id: 3,
    imgSrc:"https://luxmovies.biz/wp-content/uploads/2020/12/Dear-Zindagi-2016.jpg",
    mName:"Dear Zindagi",
    Ref:"https://www.netflix.com/in/title/80158042",
    info2:"Netflix",
    YRef:"https://www.youtube.com/watch?v=5DkO7ksXY8E",
  },
  {
    Id: 4,
    imgSrc:"https://luxmovies.biz/wp-content/uploads/2024/01/Hi-Nanna.jpg",
    mName:"Hi Nanna",
    Ref:"https://www.netflix.com/in/title/81682028",
    info2:"Netflix",
    YRef:"https://www.youtube.com/watch?v=80T1qoy9RSY&pp=ygUPaGkgcGFwYSB0cmFpbGVy",
  },
  {
    Id: 5,
    imgSrc:"https://upload.wikimedia.org/wikipedia/en/2/2e/Barfi%21_poster.jpg",
    mName:"Barfi!",
    Ref: "https://www.netflix.com/in/title/70219525",
    info2:"Netflix",
    YRef:"https://www.youtube.com/watch?v=nQ3FYUgSjC8&pp=ygUNYmFyZmkgdHJhaWxlcg%3D%3D",
  },
  {
    Id: 6,
    imgSrc:"https://upload.wikimedia.org/wikipedia/en/9/94/JaggaJasoosPoster.jpg",
    mName:"Jagga Jasos",
    Ref:"https://www.netflix.com/in/title/80104130",
    info2:"Netflix",
    YRef:"https://www.youtube.com/watch?v=YheC-4Qgoro&pp=ygULamFnZ2EgamFzb3M%3D",
  },

  {
    Id: 7,
    imgSrc:"https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSS3CqYY0yBQSZ27eXEGFtjmmlxAxVss8G77Z3LvUMWAeMB7mHB",
    mName: "Jab Harry Met Sejal",
    Ref: "https://www.netflix.com/in/title/80206847",
    info2:"Netflix",
    YRef:"https://www.youtube.com/watch?v=W5MZevEH5Ns&pp=ygUbamFiIGhhcnJ5IG1ldCBzZWphbCB0cmFpbGVy",
  },
  {
    Id: 8,
    imgSrc:"https://upload.wikimedia.org/wikipedia/en/5/5b/Attack_film_poster.jpg",
    mName:"Attack Part 1 ",
    Ref:"https://gdhubnation.gdhub.workers.dev/0:/Movies/Attack%20(2022)/Attack.Part.1.2022.2160p.ZEE5.WEB-DL.HDR.DD+5.1.H.265.mkv?a=view",
    info2:"Netflix",
    YRef:"https://www.youtube.com/watch?v=Ma3Y-qekYos&pp=ygUPYXR0YWNrIHRyYWlsZXIg",
  },
  {
    Id: 9,
    imgSrc:"https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTaiYgGGF6kx5dTUahKIV0BSNi9Q08r5HTVJf3CUXI7YKCQW0TO",
    mName:"Zindagi Na Milegi Dobara",
    Ref:"https://www.netflix.com/in/title/70202336",
    info2:"Netflix",
    YRef:"https://www.youtube.com/watch?v=FJrpcDgC3zU&pp=ygUgemluZGFnaSBuYSBtaWxlZ2kgZG9iYXJhIHRyYWlsZXI%3D",
  },
  {
    Id: 10,
    imgSrc:"https://upload.wikimedia.org/wikipedia/en/1/15/Yeh_jawani_hai_deewani.jpg",
    mName:"Yeh Jawaani Hai Deewani",
    Ref:"https://www.netflix.com/in/title/70276515",
    info2:"Netflix",
    YRef:"https://www.youtube.com/watch?v=Rbp2XUSeUNE&pp=ygUbeWUgamF3YW5pIGhlIGRpd2FuaSB0cmFpbGVy",
  },
  {
    Id: 11,
    imgSrc:"https://upload.wikimedia.org/wikipedia/en/b/b6/Tu_Jhoothi_Main_Makkaar_Title_Card.jpeg",
    mName:"Tu Jhoothi Main Makkaar",
    Ref:"https://www.netflix.com/in/title/81382254",
    info2:"Netflix",
    YRef:"https://www.youtube.com/watch?v=JzGGF4JPFIQ&pp=ygUedHUgamhvb3RoaSBtYWluIG1ha2thciB0cmFpbGVy",
  },
  {
    Id: 12,
    imgSrc:"https://upload.wikimedia.org/wikipedia/en/5/5d/Cocktail_2012_poster.jpg",
    mName:"Cocktail",
    Ref:"https://www.jiocinema.com/movies/cocktail/3486606",
    info2:"JioCinema",
    YRef:"https://www.youtube.com/watch?v=KgiYA04X3cE&pp=ygUQY29ja3RhaWwgdHJhaWxlcg%3D%3D",
  },
];

export default Sdata;
